feat: add integration test to init tunnel func
globe-and-citizen/layer8 pull request #14
Opened 2024-03-19 16:23 UTC by ternakkode

This merge request adds a unit test for the InitTunnel function in the tunnel_test.go file. The test ensures that the function initializes the tunnel correctly and returns the expected response.

2024-03-20 12:23 UTC, huzaifamk requested changes
Good work @ternakkode , can you re-open this PR into `development` branch instead of `main`? This can be merged then.

2024-03-24 06:05 UTC, NJavokhir commented on server/handlers/tunnel.go
> +	backend := r.URL.Query().Get("backend")
Good way to refactor code. I liked it.

2024-03-24 06:09 UTC, NJavokhir commented on server/handlers/tunnel_test.go
Overall, the test code appears well-written, thorough, and adheres to best practices.

2024-03-24 06:10 UTC, NJavokhir reviewed
Overall, the test code appears well-written, thorough, and adheres to best practices.

2024-03-25 11:21 UTC, huzaifamk approved these changes

2024-03-25 11:22 UTC, merged