#44 Added  a unique constraint for the backend URL
globe-and-citizen/layer8 pull request #70
Opened 2024-05-26 08:29 UTC by NJavokhir

### Issue:
The backend URL field in the tunnel API currently allows multiple clients, leading to potential data mix-up issues due to shared JWT tokens.

### Solution:
Added a unique constraint for the backend URL field in the create client form to ensure each client has a distinct backend URL.

### Changes Made:
- Implemented unique constraint for backend URL field.
- Conducted manual and automated testing.
- Resolved conflicts.
- Tagged code owner and a second developer for review.

### Testing:
Manual testing confirms proper functionality of unique constraint.

### Note:
I'll handle branch merging and deletion. Open to feedback for improvement.

2024-05-26 12:17 UTC, ternakkode commented on server/assets-v1/templates/src/pages/client_portal/register.html
> +      const responseFromBackend = ref(false);
lets change `responseFromBackend` to improve readability, something like `isBackendUrlUsed`

2024-05-26 12:18 UTC, ternakkode commented on server/assets-v1/templates/src/pages/client_portal/register.html
> +      const backend_uri_text = ref("");
incosistency, other variable is using camelCase but this variable is using snake_case

2024-05-26 12:19 UTC, ternakkode requested changes
need few adjustment

2024-06-10 13:04 UTC, NJavokhir commented
@ternakkode Can you review this PR again.

2024-06-12 08:20 UTC, ternakkode approved these changes

2024-06-15 07:57 UTC, merged